- README.md
- docs/METHODS.md
- docs/TYPES.md
- package-lock.json
- package.json
- src/index.ts
* Updates readme examples with `@reach-sh/humble-sdk` import paths
* Removes `dotenv` (related: #8)
> v1.0.2 | UPDATES README

- cli/runFetchPoolTest.mjs
- cli/runLiquidity.mjs
- cli/runSwapTest.mjs
- src/api/LiquidityProvider.Withdraw.ts
- src/api/Staker.API.ts
- src/api/Staker.Fetch.ts
- src/api/Staker.Stake.ts
- src/api/subscribeToPoolStream.ts
- src/participants/PoolAnnouncer.ts
- src/reach-helpers/index.ts
- src/types.ts
* optional balance fetch on tokenMetadata
* optional token fetch on fetchPool
> Hotfix - optionally fetch tokens on fetchPool

- package-lock.json
- package.json
- src/participants/StakingAdmin.test.ts
- src/participants/StakingAdmin.ts
https://reachsh.atlassian.net/browse/SWAP-869
Added unit test
> SWAP-869 | Prevent creating farm with non HMBL2LT staking token

- src/reach-helpers/index.ts
- Adds Algonode `MainNet` endpoints
> SWAP-922 -- AlgoNode MainNet endpoints

- cli/runFarmAnnouncerTest.mjs
- src/api/subscribeToFarmStream.ts
* enables seek-now on farm-announcer
[ Optional: change `initHumbleSDK` in `cli/index.mjs` to `initHumbleSDK({ network: "MainNet" })` if you want to test with mainnet ]
* `npm run build` in the root (don't forget to `npm i` if you haven't)
* `cd cli/ && npm i` (to make sure you have the files you just built)
* `npm run test` and enter `2` to **List Farms**. You will want to do this twice:
* Once with `n` to the **Start from now?** question (normal run: returns farms)
* Once with `y` to the **Start from now?** question (expected: no results until script times out)
> SWAP-929 -  Farm listener seekNow

- cli/index.mjs
- cli/runPoolReportTest.mjs
> CLI - Pool Report Script

- src/api/LiquidityProvider.Withdraw.ts
- src/index.ts
- src/reach-helpers/index.ts
* improved optional balance fetch
* handle axios fetch errors
> SWAP-979 patch for #774

- package-lock.json
- package.json
Version bump to `v2.1.1-beta.1`
> v2.1.1-beta.1

- cli/runFetchTokenTest.mjs
- package-lock.json
- package.json
- src/api/LiquidityProvider.Withdraw.test.ts
- src/constants.ts
- src/participants/PoolAnnouncer.ts
* fetch verified tokens by default
> v2.1.1-beta.3

- cli/runAnnounceFarmTest.mjs
* enables sequential publishing of multiple farms
> Enhanced farm announcer script

- package-lock.json
- package.json
* Bump version to `v2.1.1-beta.4`
* New Algorand block time set to `3.62s`
> 2.1.1-beta.4

- src/json/ALGO.json
- src/json/index.test.ts
- src/participants/calculateRewardsPerBlock.test.ts
* Updates algorand block-time to `3700ms` from `3620` (on `BetaNet`)
> * update blocktime to match mainnet

- cli/runFetchPoolTest.mjs
- docs/ABI.md
- makefile
- package-lock.json
- package.json
* removes mangling to prevent JS cruelty
* First implementation broke the SDK exports; this fixes them
* adds pool contract ABI JSON to docs (unlinked)
> Fix minify script

- cli/index.mjs
- cli/package-lock.json
- cli/runSandbox.mjs
- cli/selectAction.mjs
* adds new mjs file for off-sdk testing
> Adds sandbox script

- cli/index.mjs
* fixes broken pool-fetch after sandbox addition
> Hotfixes broken cli actions

- cli/runPoolReportTest.mjs
- src/constants.ts
- src/index.ts
- src/participants/PoolAdmin.ts
- src/participants/StakingAdmin.test.ts
- src/participants/StakingAdmin.ts
* updates default LP token symbol to
> Humble v3 LP token symbol

- package-lock.json
- package.json
> 3.0.0-beta.5

- package-lock.json
- package.json
> 3.0.0-beta.6

- src/api/Staker.API.ts
- src/api/subscribeToFarmStream.ts
- src/types.ts
* fix farm typedefs
* return 0,0 for initial farm rewards from announcer
> Misc fixes

- cli/package-lock.json
- package-lock.json
- package.json
> v3.0.0-beta.11

- package-lock.json
- package.json
- src/api/FarmStream.Announce.ts
- src/types.ts
* Bump to `v3.0.0-beta.12`
* Updates Farm Announcer typedefs
> v3.0.0-beta.12

- package-lock.json
- package.json
> v3.0.0-beta.13

- cli/package-lock.json
- package-lock.json
- package.json
> v3.0.0-beta.14

- cli/actions/limitOrderActions.mjs
- cli/package-lock.json
- cli/runAnnounceFarmTest.mjs
- cli/runLimitOrderTest.mjs
- package-lock.json
- package.json
- src/contracts/LimitOrder.Fetch.ts
- src/contracts/LimitOrder.Fill.ts
- src/contracts/index.ts
* enables fill-limit-order
* now returns tokens with limit-order when specified
* adds fill-limit-order cli action
* bumps to `3.0.0-beta.18`
> SWAP-1287 (v3.0.0-beta.18)
